services:
  server:
    build:
      context: ./nlw-journey-server
      dockerfile: Dockerfile
    container_name: nlw-journey-server
    ports:
      - "8080:8080"
    env_file: .env
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - database
    restart: unless-stopped
    networks:
      - app-network
  client:
    build:
      context: ./nlw-journey-app
      dockerfile: Dockerfile
    container_name: nlw-journey-app
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - app-network
  database:
    image: postgres:16
    container_name: nlw-journey-database
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nlw-journey-app/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network:
    driver: bridge
