import { ThemeProvider } from '@/components/ThemeProvider';
import { Toaster } from '@components/ui/toaster';
import { cn } from '@lib/utils';
import type { Metadata } from 'next';
import { Inter as FontSans } from 'next/font/google';
import './globals.css';

type RootLayoutProps = Readonly<{
    children: React.ReactNode;
}>;

export const metadata: Metadata = {
    title: 'NLW Journey',
    description: 'Generated by create next app',
    icons: '/Vector.svg',
};

const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
});

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="pt-BR">
            <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
                <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                    {children}
                </ThemeProvider>
                <Toaster />
            </body>
        </html>
    );
}
